export const languages = {
    'ar-EG': 'Arabic, Eygpt (العربية، مصر)',
    bg: 'Bulgarian (български)',
    'zh-CN': 'ChineseCN (简体中文)',
    'zh-TW': 'ChineseTW (繁體中文)',
    hr: 'Croatian (Hrvatski)',
    cs: 'Czech (čeština)',
    da: 'Danish (Dansk)',
    nl: 'Dutch (Nederlands)',
    'en-GB': 'English (United Kingdom)',
    'en-US': 'English (United States)',
    fi: 'Finnish (Suomi)',
    fr: 'French (Français)',
    de: 'German (Deutsch)',
    el: 'Greek (Ελληνικά)',
    hi: 'Hindi (हिन्दी)',
    hu: 'Hungarian (Magyar)',
    id: 'Indonesian (Bahasa Indonesia)',
    it: 'Italian (Italiano)',
    ja: 'Japanese (日本語)',
    ko: 'Korean (한국어)',
    lt: 'Lithuanian (Lietuvių)',
    no: 'Norwegian (Norsk)',
    pl: 'Polish (Polski)',
    'pt-BR': 'PortugueseBR (Português)',
    ro: 'Romanian (Română)',
    ru: 'Russian (Русский)',
    'es-ES': 'SpanishES (Español)',
    'sv-SE': 'Swedish (Svenska)',
    th: 'Thai (ไทย)',
    tr: 'Turkish (Türkçe)',
    uk: 'Ukrainian (Українська)',
    vi: 'Vietnamese (Tiếng Việt)',
};
